name: force
version: 0.3.0
author: Joris Hermans <hermansj@gmail.com>
description: A real time web framework for dart, embracing websockets, making communication easier
homepage: https://github.com/jorishermans/dart-force
dependencies:
  unittest: '>=0.9.0 <0.9.1'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  route: '>=0.4.0 <0.5.0'
  uuid: '0.2.1'