name: force
version: 0.4.1
author: Joris Hermans <hermansj@gmail.com>
description: A real time web framework for dart, embracing websockets, making communication even better
homepage: https://github.com/jorishermans/dart-force
dependencies:
  http: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  uuid: '>=0.3.0 <0.4.0'
  forcemvc: '>=0.3.0 <0.4.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.11.1'
  mock: '>=0.11.0 <0.11.1'
  
  