name: force
version: 0.3.3+4
author: Joris Hermans <hermansj@gmail.com>
description: A real time web framework for dart, embracing websockets, making communication even better
homepage: https://github.com/jorishermans/dart-force
dependencies:
  http: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  uuid: '0.2.2'
  forcemvc: '0.1.7'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'