name: force
version: 0.6.2
author: Joris Hermans <hermansj@gmail.com>
description: A real time web framework for dart, embracing websockets, making communication even better
homepage: https://github.com/ForceUniverse/dart-force
dependencies:
  logging: '>=0.9.0 <0.10.0'
  uuid: '>=0.4.1 <0.5.0'
  forcemvc: '>=0.7.0 <0.7.1'
  cargo: '>=0.7.0 <0.8.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.11.1'
  mock: '>=0.11.0 <0.11.1'
  
  